[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
default_command = "{{ZOMBIENET_NATIVE_BINARY_PREFIX}}polkadot"

[[relaychain.node_groups]]
name = "validator"
count = 4
args = ["--log=beefy=debug", "--beefy", "--enable-offchain-indexing=true"]
